#!/usr/bin/env python3
"""Generate/check shared camera vectors using the unchanged Phase 1.1 helpers.

Python is build/test tooling only. The native test compiles the generated header;
the executable never loads Python or reads Python code in its frame loop.
"""
import argparse
import json
from pathlib import Path
import sys

HOST = Path(__file__).resolve().parents[1]
ROOT = HOST.parents[1]
sys.path.insert(0, str(ROOT / "examples/cordel_viewport/game/python-packages"))
from cordel_spike.math3d import Camera
from cordel_spike.input_state import ActionState


def generate():
    cases = []
    for yaw, pitch, width, height in ((0, 0, 850, 480), (90, 0, 500, 500),
                                      (-90, 0, 320, 500), (32, 27, 850, 480),
                                      (450, 999, 850, 480), (-450, -999, 500, 500)):
        camera = Camera(position=(2, 3, 4), yaw=yaw, pitch=pitch)
        cases.append(dict(yaw=yaw, pitch=pitch, width=width, height=height,
                          clamped_yaw=camera.yaw, clamped_pitch=camera.pitch,
                          forward=camera.forward(), right=camera.right(),
                          view=camera.view(), projection=camera.projection(width, height)))
    movements = []
    action_names = ("forward", "backward", "left", "right", "up", "down", "sprint")
    for active in (("forward",), ("backward",), ("left",), ("right",), ("up",), ("down",),
                   ("forward", "right"), ("forward", "sprint"), ("up", "sprint")):
        state = ActionState()
        for name in active:
            state.key_down(name, name)
        camera = Camera(position=(0, 0, 0), pitch=0)
        camera.move(state, 1.0)
        movements.append(dict(actions=[name in active for name in action_names],
                              dt=1, expected=camera.position))
    fixture = json.loads((ROOT / "examples/cordel_viewport/game/assets/cordel_scene.gltf").read_text())
    return dict(schema=1, convention="RH +Y up -Z forward metres, row-major column vectors",
                cameras=cases, movements=movements,
                nodes=[dict(name=n["name"], translation=n["translation"]) for n in fixture["nodes"]])


def header(data):
    def array(values):
        return "{" + ",".join("true" if v is True else "false" if v is False else repr(float(v)) for v in values) + "}"
    lines = ["// Generated by tools/goldens.py from shared JSON and Phase 1.1 math. MIT.",
             "#pragma once", '#include "cordel/logic.hpp"', "namespace cordel::goldens {",
             "struct CameraCase { double yaw,pitch; int width,height; double clamped_yaw,clamped_pitch; Vec3 forward,right; Mat4 view,projection; };",
             "inline const CameraCase cameras[] = {"]
    for c in data["cameras"]:
        lines.append("{" + ",".join([repr(c["yaw"]), repr(c["pitch"]), str(c["width"]), str(c["height"]),
                                   repr(c["clamped_yaw"]), repr(c["clamped_pitch"]), array(c["forward"]),
                                   array(c["right"]), array(c["view"]), array(c["projection"])]) + "},")
    lines += ["};", "struct MoveCase { std::array<bool,7> actions; double dt; Vec3 expected; };",
              "inline const MoveCase movements[] = {"]
    for m in data["movements"]:
        lines.append("{" + array(m["actions"]) + "," + repr(m["dt"]) + "," + array(m["expected"]) + "},")
    lines += ["};", "struct NodeCase { const char* name; Vec3 translation; };", "inline const NodeCase nodes[] = {"]
    for node in data["nodes"]:
        lines.append("{" + json.dumps(node["name"]) + "," + array(node["translation"]) + "},")
    lines += ["};", "}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = generate()
    products = {HOST / "tests/goldens.json": json.dumps(data, indent=2) + "\n",
                HOST / "tests/goldens.hpp": header(data)}
    for path, text in products.items():
        if args.check:
            if path.read_text() != text:
                raise SystemExit(f"Shared golden mismatch: {path}; regenerate deliberately")
        else:
            path.write_text(text)
    print("Phase 1.1 Python/shared JSON/native header agreement: 6 camera, 9 movement, 7 node vectors")
